checkpoint: logs/videosaur/2026-06-11-15-51-53_lerobot_something_something_v2_2/checkpoints/step=1000.ckpt
model_config: configs/videosaur/lerobot_something_something_v2.yml
n_slots: 6
input:
  path: docs/static/videos/video.mp4
  type: video
  transforms:
    use_movi_normalization: true
    dataset_type: video
    input_size: 224
output:
  save_path: docs/static/videos/video_masks.mp4